spring:
  application:
    name: trade-mcp-server
  ai:
    mcp:
      server:
        name: trade-mcp-server
        version: 1.0.0
        type: sync
        protocol: streamable
        stdio: false
        enabled: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

groww:
  base-url: https://api.groww.in/v1/
  api-key: ${GROWW_API_KEY}
  secret: ${GROWW_SECRET_KEY}
  token-url: token/api/access
  historic-data-url: historical/candles

server:
  port: 8082
  connection-timeout: 90s