spring:
  application:
    name: trade-mcp-server
  ai:
    mcp:
      server:
        name: trade-mcp-server
        version: 1.0.0
        type: sync
        protocol: streamable
        stdio: false
        enabled: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

groww:
  base-url: https://api.groww.in/v1/
  api-key: ${GROWW_API_KEY}
  secret: ${GROWW_SECRET_KEY}
  token-url: token/api/access
  historic-data-url: historical/candle/range
  holdings-url: holdings/user
  positions-url: positions/user
  positions-trading-url: positions/trading-symbol
  order-list-url: order/list
  create-order-url: order/create
  order-details-url: order/details/
  modify-order-url: order/modify
  cancel-order-url: order/cancel
  order-status-url: order/status/
  order-status-reference-url: order/status/reference/
  order-trades-url: order/trades/

server:
  port: 8082